/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Qtrip_QA.app;

import Qtrip_QA.list.LinkedList;

import static Qtrip_QA.utilities.StringUtils.join;
import static Qtrip_QA.utilities.StringUtils.split;
import static Qtrip_QA.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
